[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"

auto_detect_solc = true

sender = '0x9dF0C6b0066D5317aA5b38B36850548DaCCa6B4e'
tx_origin = '0x9dF0C6b0066D5317aA5b38B36850548DaCCa6B4e'